version: "3.9"
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./api/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${DOCKER_WEBSERVER_API_PORT:-8000}:80"
      - "${DOCKER_WEBSERVER_CLIENT_PORT:-3000}:81"
    depends_on:
      - api
      - client

  api:
    image: spa/api
    build:
      context: ./api
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  client:
    image: spa/client
    build:
      context: ./client

  redis:
    image: redis:7.0.9-alpine
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local