version: "3.8"
name: "spa-stg"
services:
  webserver:
    ports:
      - "8002:80"

  api:
    environment:
      - APP_ENV=staging
    volumes:
      - ./api/local.ini:/usr/local/etc/php/conf.d/local.ini

  db:
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  client:
    build:
      target: build-staging
    environment:
      - PORT=3000
      - NODE_ENV=staging