version: "3.8"
name: "spa-dev"
services:
  webserver:
    ports:
      - "${DOCKER_PORT_WEBSERVER:-8000}:80"

  api:
    build:
      args:
        MODE: development
    volumes:
      - ./api/:/var/www/
      - /var/www/vendor
      - ./api/local.ini:/usr/local/etc/php/conf.d/local.ini

  db:
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  client:
    build:
      target: serve-stage
      args:
        MODE: development
    volumes:
      - ./client/src/:/app/src/
    environment:
      - APP_URL=http://client.localhost:${DOCKER_PORT_WEBSERVER:-8000}